### ISSUE TITLE
Fatal error: Uncaught Algolia\AlgoliaSearch\Exceptions\NotFoundException:

### ISSUE THREAD

**Issue by amrutadotorg** [helsingborg-stad/algolia-index#1]
Hi I installed your plugin on amruta.org, added all constans
also optional:
`define('ALGOLIAINDEX_INDEX_NAME', 'searchable_posts'); 
`
but when I want search then I'm getting 
```
Fatal error: Uncaught Algolia\AlgoliaSearch\Exceptions\NotFoundException: Index www-amruta-org does not exist in /var/app/current/wp-content/plugins/algolia-index-master/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:208 Stack trace: #0 /var/app/current/wp-content/plugins/algolia-index-master/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(158): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse(Object(GuzzleHttp\Psr7\Response), Object(Algolia\AlgoliaSearch\Http\Psr7\Request)) #1 /var/app/current/wp-content/plugins/algolia-index-master/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(78): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request('POST', '/1/indexes/www-...', Object(Algolia\AlgoliaSearch\RequestOptions\RequestOptions), Array, 5) #2 /var/app/current/wp-content/plugins/algolia-index-master/vendor/algolia/algoliasearch-client-php/src/SearchIndex.php(62): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->read('POST', '/1/indexes in /var/app/current/wp-content/plugins/algolia-index-master/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php on line 208
There has been a critical error on this website.
```
could you please tell me what could be an issue?

I did not install algolia-index-modularity-addon
thank you

**Comment by sebastianthulin** [comment]
Hi! 

Try to visit the options page and click "save" button. This will create the index if it dosen't already exists. You also have the option to create it manually in the algolia dashboard, however algolia-index plugin will also set som default settings on the index that you may benefit from.

**Comment by amrutadotorg** [comment]
thank you for your prompt reply
now I'm getting

wp algolia-index build
`
Starting index build for site https://www.amruta.org
Indexing 'Adi Shakti Puja' of posttype post
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 2000 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:207
Stack trace:
#0 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(162): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(109): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish in /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 207
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 2000 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:207
Stack trace:
#0 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(162): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(109): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish in /home/user/git/amruta/html/wp-content/plugins/algolia-index-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 207
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.`

**Comment by sebastianthulin** [comment]
Looks like a connection error between your server and algolia servers. This is an issue that are contained in the guzzle package implemented by algolia vendor package. Therefore we cannot provide any recommendations or an resolution to the issue. Please refer to the respective vendors support pages.

**Comment by amrutadotorg** [comment]
Thank you, that's really strange. Building the index with the plugin https://github.com/WebDevStudios/wp-search-with-algolia 
via the wpCLI works without any connection issues

**Comment by sebastianthulin** [comment]
Have you tried to save a post? It that works I would agree on that the issue might be in algolia-index plugin. We have hade some issues before with none utf-8 chars, can you try to create a new empty post only containing a-z letters?

**Comment by sebastianthulin** [comment]
If this resolves as a utf-8 issue, then you might use the AlgoliaIndex/Record filter to encode whatever content you want to index before submission. You are also welcome to submit a pull-request. Thanks!
